### PR TITLE
Move the device_map into a separate library file

### PR DESCRIPTION
**Pull request by mattface**
Having the device_map as an import means the original
lava-kernel-ci-job-creator script becomes more manageable,
and allows other new scripts to be created that share the
same data.

### CODE REVIEW

**Comment by MiloCasagrande** [comment]
Since you are at it, would you mind fixing the new device_map indentation to be more "pythonic"?
Like:

``` python
bcm2835_rpi_b_plus = {
    'device_type': 'bcm2835-rpi-b-plus',
    'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
    'kernel_defconfig_blacklist': [],
    'defconfig_blacklist': ['arm-allmodconfig'],
    'kernel_blacklist': [],
    'nfs_blacklist': [],
    'lpae': False,
    'fastboot': False
}
```

If it's too much of an hassle, I'll do it at a later time: I have a save function that automagically fixes all of that.

**Comment by MiloCasagrande** [comment]
Also, before merging this one, I'd like us to merge #39 (need to ping Kevin and/or Tyler to take a look at that one).

**Comment by mattface** [comment]
I don't have a pythonator 2000, so leave that to you to clean up if you like :)

But yes, #39 would need to be updated in the new device_map, so agreed this should wait for it.

**Comment by mattface** [comment]
Updated device_map to reflect recent changes.

**Pull request merged**
